---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{- include "users.secret" . | indent 1}}
spec:
  provider: aws
  secretObjects:
  - secretName: secret-{{ .Values.secretsName }}
    type: Opaque
    data:
  {{- range $secret := .Values.secretsParameters }}
    - objectName: {{ $secret }}
      key: {{ $secret }}
  {{- end  }}
  parameters:
    objects: |
        - objectName: {{ .Values.secretsName }}
          objectType: secretsmanager
          jmesPath:
      {{- range $secret := .Values.secretsParameters }}
            - path: {{ $secret }}
              objectAlias: {{ $secret }}
      {{- end  }}
